controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left_motor"]
    right_wheel_names: ["right_motor"]

    wheel_separation: 0.4
    wheel_radius: 0.075

    # The real separation between wheels is not resulting in a perfect odometry
    wheel_separation_multiplier: 1.0

    use_stamped_vel: false
    base_frame_id: "base_link"
    
